// Mapa de geoTargetConstants do Google Ads -> país.
// Lista compacta dos principais países usados em arbitragem.
// Fonte: https://developers.google.com/google-ads/api/data/geotargets
export const COUNTRY_BY_ID: Record<string, { code: string; name: string }> = {
  "2076": { code: "BR", name: "Brasil" },
  "2840": { code: "US", name: "Estados Unidos" },
  "2348": { code: "HU", name: "Hungria" },
  "2724": { code: "ES", name: "Espanha" },
  "2620": { code: "PT", name: "Portugal" },
  "2484": { code: "MX", name: "México" },
  "2032": { code: "AR", name: "Argentina" },
  "2152": { code: "CL", name: "Chile" },
  "2170": { code: "CO", name: "Colômbia" },
  "2196": { code: "CY", name: "Chipre" },
  "2604": { code: "PE", name: "Peru" },
  "2604" : { code: "PE", name: "Peru" },
  "2862": { code: "VE", name: "Venezuela" },
  "2250": { code: "FR", name: "França" },
  "2276": { code: "DE", name: "Alemanha" },
  "2380": { code: "IT", name: "Itália" },
  "2826": { code: "GB", name: "Reino Unido" },
  "2528": { code: "NL", name: "Holanda" },
  "2056": { code: "BE", name: "Bélgica" },
  "2752": { code: "SE", name: "Suécia" },
  "2208": { code: "DK", name: "Dinamarca" },
  "2246": { code: "FI", name: "Finlândia" },
  "2578": { code: "NO", name: "Noruega" },
  "2616": { code: "PL", name: "Polônia" },
  "2203": { code: "CZ", name: "República Tcheca" },
  "2703": { code: "SK", name: "Eslováquia" },
  "2642": { code: "RO", name: "Romênia" },
  "2100": { code: "BG", name: "Bulgária" },
  "2300": { code: "GR", name: "Grécia" },
  "2792": { code: "TR", name: "Turquia" },
  "2643": { code: "RU", name: "Rússia" },
  "2804": { code: "UA", name: "Ucrânia" },
  "2156": { code: "CN", name: "China" },
  "2392": { code: "JP", name: "Japão" },
  "2410": { code: "KR", name: "Coreia do Sul" },
  "2356": { code: "IN", name: "Índia" },
  "2360": { code: "ID", name: "Indonésia" },
  "2764": { code: "TH", name: "Tailândia" },
  "2704": { code: "VN", name: "Vietnã" },
  "2608": { code: "PH", name: "Filipinas" },
  "2458": { code: "MY", name: "Malásia" },
  "2702": { code: "SG", name: "Singapura" },
  "2036": { code: "AU", name: "Austrália" },
  "2554": { code: "NZ", name: "Nova Zelândia" },
  "2124": { code: "CA", name: "Canadá" },
  "2818": { code: "EG", name: "Egito" },
  "2710": { code: "ZA", name: "África do Sul" },
  "2566": { code: "NG", name: "Nigéria" },
  "2404": { code: "KE", name: "Quênia" },
  "2784": { code: "AE", name: "Emirados Árabes" },
  "2682": { code: "SA", name: "Arábia Saudita" },
  "2376": { code: "IL", name: "Israel" },
  "2372": { code: "IE", name: "Irlanda" },
  "2756": { code: "CH", name: "Suíça" },
  "2040": { code: "AT", name: "Áustria" },
  "2344": { code: "HK", name: "Hong Kong" },
  "2158": { code: "TW", name: "Taiwan" },
  "2446": { code: "MO", name: "Macau" },
  "2188": { code: "CR", name: "Costa Rica" },
  "2591": { code: "PA", name: "Panamá" },
  "2858": { code: "UY", name: "Uruguai" },
  "2068": { code: "BO", name: "Bolívia" },
  "2218": { code: "EC", name: "Equador" },
  "2600": { code: "PY", name: "Paraguai" },
};
